# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ServerBody_pb2 as ServerBody__pb2


class BodyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVideosX = channel.unary_unary(
                '/ServerBody.Body/GetVideosX',
                request_serializer=ServerBody__pb2.VideoListXRequest.SerializeToString,
                response_deserializer=ServerBody__pb2.VideoListXReply.FromString,
                )
        self.SearchVideosX = channel.unary_unary(
                '/ServerBody.Body/SearchVideosX',
                request_serializer=ServerBody__pb2.VideoListXRequest.SerializeToString,
                response_deserializer=ServerBody__pb2.VideoListXReply.FromString,
                )
        self.GetHeadersX = channel.unary_unary(
                '/ServerBody.Body/GetHeadersX',
                request_serializer=ServerBody__pb2.VideoHeaderXRequest.SerializeToString,
                response_deserializer=ServerBody__pb2.VideoHeaderXReply.FromString,
                )


class BodyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetVideosX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchVideosX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHeadersX(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BodyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVideosX': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideosX,
                    request_deserializer=ServerBody__pb2.VideoListXRequest.FromString,
                    response_serializer=ServerBody__pb2.VideoListXReply.SerializeToString,
            ),
            'SearchVideosX': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchVideosX,
                    request_deserializer=ServerBody__pb2.VideoListXRequest.FromString,
                    response_serializer=ServerBody__pb2.VideoListXReply.SerializeToString,
            ),
            'GetHeadersX': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeadersX,
                    request_deserializer=ServerBody__pb2.VideoHeaderXRequest.FromString,
                    response_serializer=ServerBody__pb2.VideoHeaderXReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServerBody.Body', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Body(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVideosX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerBody.Body/GetVideosX',
            ServerBody__pb2.VideoListXRequest.SerializeToString,
            ServerBody__pb2.VideoListXReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchVideosX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerBody.Body/SearchVideosX',
            ServerBody__pb2.VideoListXRequest.SerializeToString,
            ServerBody__pb2.VideoListXReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHeadersX(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerBody.Body/GetHeadersX',
            ServerBody__pb2.VideoHeaderXRequest.SerializeToString,
            ServerBody__pb2.VideoHeaderXReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
