# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerBody.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ServerBody.proto\x12\nServerBody\"#\n\x11VideoListXRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"B\n\x0fVideoListXReply\x12/\n\nVideoListX\x18\x01 \x03(\x0b\x32\x1b.ServerBody.VideoListXModel\"\xa0\x01\n\x0fVideoListXModel\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07Picture\x18\x04 \x01(\t\x12\x10\n\x08\x43\x61tegory\x18\x05 \x01(\t\x12\r\n\x05Views\x18\x06 \x01(\x05\x12\x0c\n\x04Year\x18\x07 \x01(\x05\x12\x10\n\x08\x44irector\x18\x08 \x01(\t\x12\x0c\n\x04\x43\x61st\x18\t \x01(\t\"%\n\x13VideoHeaderXRequest\x12\x0e\n\x06\x66ilter\x18\x01 \x01(\t\"H\n\x11VideoHeaderXReply\x12\x33\n\x0cVideoHeaderX\x18\x01 \x03(\x0b\x32\x1d.ServerBody.VideoHeaderXModel\"e\n\x11VideoHeaderXModel\x12\n\n\x02ID\x18\x01 \x01(\x05\x12\x10\n\x08ID_VIDEO\x18\x02 \x01(\x05\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12\x0f\n\x07Picture\x18\x05 \x01(\t2\xf2\x01\n\x04\x42ody\x12J\n\nGetVideosX\x12\x1d.ServerBody.VideoListXRequest\x1a\x1b.ServerBody.VideoListXReply\"\x00\x12M\n\rSearchVideosX\x12\x1d.ServerBody.VideoListXRequest\x1a\x1b.ServerBody.VideoListXReply\"\x00\x12O\n\x0bGetHeadersX\x12\x1f.ServerBody.VideoHeaderXRequest\x1a\x1d.ServerBody.VideoHeaderXReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ServerBody_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOLISTXREQUEST._serialized_start=32
  _VIDEOLISTXREQUEST._serialized_end=67
  _VIDEOLISTXREPLY._serialized_start=69
  _VIDEOLISTXREPLY._serialized_end=135
  _VIDEOLISTXMODEL._serialized_start=138
  _VIDEOLISTXMODEL._serialized_end=298
  _VIDEOHEADERXREQUEST._serialized_start=300
  _VIDEOHEADERXREQUEST._serialized_end=337
  _VIDEOHEADERXREPLY._serialized_start=339
  _VIDEOHEADERXREPLY._serialized_end=411
  _VIDEOHEADERXMODEL._serialized_start=413
  _VIDEOHEADERXMODEL._serialized_end=514
  _BODY._serialized_start=517
  _BODY._serialized_end=759
# @@protoc_insertion_point(module_scope)
